name: Benchmark

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Previous state
      working-directory: previous
      run: |
        go test -bench=. -benchmem


    - name: PR state
      working-directory: pr
      run: |
        go test -bench=. -benchmem
